services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_container
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env

  vuejs:
    build:
      context: ../Nowtes
      dockerfile: Dockerfile
    container_name: vuejs_container
    ports:
      - "8080:8080"
    env_file:
      - ../Nowtes/.env

volumes:
  mysql_data:
